apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m92x381jc-python
  janus-idp.io/tekton: m92x381jc-python
  backstage.io/kubernetes-id: m92x381jc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m92x381jc-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
